name: CI/CD TP Vue

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v1
        with:
          host: 193.70.113.80
          username: debian
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/debian/tp-vuejs
            bash deploy.sh